site_name: SBC - Allwinner A13
site_url: https://vd-rd.github.io/sbc_allwinner_a13
theme:
  name: material
  palette:
    primary: lime
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Hardware: 
    - hardware.md
    - Build your own: hardware-ref/build-your-own.md
    - Introduction: hardware-ref/introduction.md
    - Schematics: hardware-ref/schematics.md
    - PCB: hardware-ref/pcb.md
    - BOM: hardware-ref/bom.md
    - Components: hardware-ref/components.md 
  - Software: 
    - software.md
    - Compile from source: software-ref/compile-from-source.md
    - Introduction: software-ref/introduction.md
